# Generated by Django 2.2.13 on 2020-08-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('channel', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='канал')),
                ('time_sent', models.DateTimeField(verbose_name='отправлено')),
                ('value', models.FloatField(verbose_name='значение')),
            ],
            options={
                'verbose_name': 'показания датчика',
                'verbose_name_plural': 'показания датчиков',
                'ordering': ['time_sent'],
                'get_latest_by': 'time_sent',
            },
        ),
        migrations.CreateModel(
            name='ThresholdModel',
            fields=[
                ('channel', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='канал')),
                ('min_value', models.FloatField(verbose_name='минимум')),
                ('max_value', models.FloatField(verbose_name='максимум')),
                ('flag', models.CharField(max_length=256, verbose_name='флаг')),
            ],
            options={
                'verbose_name': 'порог датчиков',
                'verbose_name_plural': 'пороги датчиков',
            },
        ),
    ]
