# Generated by Django 2.2.13 on 2020-08-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdmodel',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='максимум'),
        ),
        migrations.AlterField(
            model_name='thresholdmodel',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='минимум'),
        ),
    ]
