# Generated by Django 2.2.13 on 2020-08-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome2_app', '0003_actuatormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTagModel',
            fields=[
                ('data', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='метка')),
                ('name', models.CharField(max_length=32, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'RFID-метка',
                'verbose_name_plural': 'RFID-метки',
            },
        ),
        migrations.AlterField(
            model_name='thresholdmodel',
            name='flag',
            field=models.CharField(max_length=128, verbose_name='флаг'),
        ),
    ]
